import { Filter, LayoutGrid, List, Plus, Search, Trash2, Users } from 'lucide-react';
import { useMemo, useState } from 'react';
import { initialTasks } from '../data/mockData';

const columns = [
  { id: 'todo', label: 'To do' },
  { id: 'in-progress', label: 'In progress' },
  { id: 'review', label: 'For review' },
  { id: 'done', label: 'Completed' },
];

export default function Tasks() {
  const [taskItems, setTaskItems] = useState(initialTasks);
  const [scope, setScope] = useState('all');
  const [query, setQuery] = useState('');
  const [showCreate, setShowCreate] = useState(false);
  const [taskPendingDelete, setTaskPendingDelete] = useState(null);
  const tasks = useMemo(()=>taskItems.filter(t => (scope === 'all' || t.type === scope) && t.title.toLowerCase().includes(query.toLowerCase())),[scope,query,taskItems]);
  const removeTask = () => { setTaskItems(items => items.filter(task => task.id !== taskPendingDelete.id)); setTaskPendingDelete(null); };
  return <section className="page-block"><div className="page-heading"><div><span className="eyebrow">Workspace</span><h1>Tasks</h1><p>Manage personal priorities and team delivery in one place.</p></div><button className="button button-primary" onClick={()=>setShowCreate(true)}><Plus size={17}/> Create task</button></div><div className="task-toolbar"><div className="segmented" aria-label="Task scope">{['all','personal','team'].map(item=><button key={item} className={scope===item?'active':''} onClick={()=>setScope(item)}>{item[0].toUpperCase()+item.slice(1)}</button>)}</div><div className="toolbar-actions"><label className="table-search"><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search by task or project" aria-label="Search tasks"/></label><button className="button button-secondary button-small"><Filter size={16}/> Filter</button><div className="view-toggle"><button className="active" aria-label="Board view" title="Board view"><LayoutGrid size={17}/></button><button aria-label="List view" title="List view"><List size={17}/></button></div></div></div><div className="kanban-board">{columns.map(column=>{const columnTasks=tasks.filter(t=>t.status===column.id);return <section className="kanban-column" key={column.id}><div className="kanban-heading"><div><span className={`column-dot ${column.id}`}/><b>{column.label}</b><small>{columnTasks.length}</small></div><button aria-label={`Add task to ${column.label}`} title={`Add task to ${column.label}`} onClick={()=>setShowCreate(true)}><Plus size={16}/></button></div><div className="kanban-cards">{columnTasks.map(task=><TaskCard task={task} key={task.id} onDelete={()=>setTaskPendingDelete(task)}/>)}{columnTasks.length===0&&<div className="column-empty"><b>No tasks here</b><span>Move a task here or start from a new one.</span></div>}<button className="add-card" onClick={()=>setShowCreate(true)}><Plus size={15}/> Add task</button></div></section>})}</div>{showCreate&&<CreateTask onClose={()=>setShowCreate(false)}/>} {taskPendingDelete&&<DeleteTask task={taskPendingDelete} onCancel={()=>setTaskPendingDelete(null)} onDelete={removeTask}/>}</section>;
}

function TaskCard({task,onDelete}) { return <article className="kanban-card"><div className="card-top"><span className={`task-kind ${task.type}`}>{task.type === 'team' ? <Users size={12}/> : null}{task.type}</span><button className="card-delete-action" aria-label={`Delete ${task.title}`} title="Delete task" onClick={onDelete}><Trash2 size={15}/></button></div><h3>{task.title}</h3><p>{task.project}</p><div className="card-progress"><div><span><i style={{width:`${task.progress}%`}}/></span><small>{task.progress}%</small></div></div><div className="card-footer"><span className={`priority-label ${task.priority}`}>{task.priority}</span><span className="card-due">{task.due}</span><div className="avatar-stack">{task.assignees.map(a=><span className="avatar tiny avatar-plum" key={a}>{a}</span>)}</div></div><button className="card-open-action">Open task <span aria-hidden="true">→</span></button></article>; }

function CreateTask({onClose}) { const [type,setType]=useState('personal'); return <div className="modal-backdrop" onMouseDown={onClose}><div className="modal" onMouseDown={e=>e.stopPropagation()}><div className="modal-head"><div><span className="eyebrow">New task</span><h2>Create a task</h2></div><button onClick={onClose} aria-label="Close">×</button></div><div className="type-select"><button className={type==='personal'?'selected':''} onClick={()=>setType('personal')}><b>Personal</b><small>Private to you</small></button><button className={type==='team'?'selected':''} onClick={()=>setType('team')}><b>Team</b><small>Assign or open for requests</small></button></div><label className="field-label">Task title<input placeholder="What needs to be done?" autoFocus/></label><div className="form-grid"><label className="field-label">Due date<input type="date"/></label><label className="field-label">Priority<select><option>Medium</option><option>High</option><option>Low</option></select></label></div><label className="field-label">Description<textarea placeholder="Add context, expectations, or a checklist" rows="4"/></label><div className="modal-actions"><button className="button button-secondary" onClick={onClose}>Cancel</button><button className="button button-primary" onClick={onClose}>Create task</button></div></div></div>; }

function DeleteTask({task,onCancel,onDelete}) { return <div className="modal-backdrop" onMouseDown={onCancel}><div className="modal delete-modal" onMouseDown={event=>event.stopPropagation()}><span className="danger-icon">!</span><h2>Delete “{task.title}”?</h2><p>This removes the task and its progress from the workspace. This action cannot be undone.</p><div className="modal-actions"><button className="button button-secondary" onClick={onCancel}>Keep task</button><button className="button button-danger" onClick={onDelete}>Delete task permanently</button></div></div></div>; }
